file(READ "../Makefile" v)
string(REGEX MATCH "MAJOR = ([0-9]*)" _ "${v}")
set(MAJOR_VERSION ${CMAKE_MATCH_1})
string(REGEX MATCH "MINOR = ([0-9]*)" _ "${v}")
set(MINOR_VERSION ${CMAKE_MATCH_1})
string(REGEX MATCH "PATCH_LEVEL = ([0-9]*)" _ "${v}")
set(PATCH_LEVEL ${CMAKE_MATCH_1})
string(TIMESTAMP YICES_COMPILATION_DATE "%Y-%m-%d")
file(READ "api/yices_version_template.txt" v)
string(REPLACE "YICES_VERSION" "${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_LEVEL}" v "${v}")
string(REPLACE "YICES_COMPILATION_DATE" "${YICES_COMPILATION_DATE}" v "${v}")
string(REPLACE "YICES_ARCH" "unknown" v "${v}")
string(REPLACE "YICES_BUILD_MODE" "${CMAKE_BUILD_TYPE}" v "${v}")
string(REPLACE "REVISION" "0" v "${v}")
if(EXISTS "api/yices_release_version.c")
  file(READ "api/yices_release_version.c" old)
endif()
if(NOT v STREQUAL "${old}")
  file(WRITE "api/yices_release_version.c" "${v}")
endif()
